name: Generate images

on:
  push:
    branches:
    - '**'
    paths:
    - '.github/workflows/generate-images.yml'
    - 'images/generated/**'
    - '**.drawio'
    - '**.puml'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: run Action
      uses: ichderjens/firstAction/action.yml@v1
      with:
        project: Mainline_OPB2
  
    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.time }}"
