name: update Polarion

on:
  pull_request:
  push:
    branches:
      - main
      - tim-epa-fdv
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: run Action
      uses: ichderjens/firstAction@main
      with:
        project: Mainline_OPB2
  
    - name: Print Output
      id: output
      run: echo "${{ steps.test-action.outputs.time }}"
